import { Roboto } from 'next/font/google'

import "./globals.css";
import NavHeader from "../components/Layout/Nav/nav";

const roboto = Roboto({
  weight: ['400', '700', '500', '300'],
  subsets: ['latin'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className={roboto.className}
      >
        <NavHeader/>
        {children}
      </body>
    </html>
  );
}
